version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  deploy:
      executor: gcp-cli/default
      working_directory: ~/repo
      steps:
          - gcp-cli/install
          - gcp-cli/initialize
          - run:
                command: gsutil cp ~/composer-demo/quick1.py gs://asia-northeast1-example-env-c50e72d7-bucket/dags/
workflows:
  main:
    jobs:
      - deploy:
            context: myContext