version: 2.1

orbs:
  python: circleci/gcp-cli@1.8.4

jobs:
  deploy:
      working_directory: ~/repo
      steps:
          - gcp-cli/install_and_initialize_cli:
                context: myContext
                executor:
                    gcp-cli/default:
                        python-version: 3.7
          - run:
                command: gsutil cp "quick1.py" "gs://asia-northeast1-example-env-c50e72d7-bucket/dags/"
workflows:
  main:
    jobs:
      - deploy
